README.md

When following these steps on Ubuntu 14.04 Server edition, I also needed these two packages to get through the build process.

Add dependencies needed on Ubuntu 14.04

---

Makefile

It seems the output of `uname -p` (processor) is not as consistent for
returning "x86_64" as `uname -m` on multiple platforms.
On an Arch Linux system, `-p` returns "unknown" whilst `-m` correctly
returns "x86_64`.
On a 2009 MacBook Pro (64bit Core 2 Duo) running El Capitan `-p` returns
"i386" and `-m` again returns "x86_64".
Both `-p` and `-m` returns "x86_64" on tests boxes of Ubuntu Wiley,
Scientific Linux and Fedora.

Use `uname -m` for `make` 64bit compatibility check

---

board/nerves-common/rootfs-additions/etc/erl_inetrc
package/nerves-config/erlinit.config.m4

This is going to require the addition of ERL_INETRC=/etc/erl_inetrc to other targets. This is a proposition, I have found that the `inet_res` resolver operates better on nerves than the native resolver. This fixes issues with distributed erlang

Change erlang inet configuration to use the inet_res resolver.

---

scripts/rel2fw.sh

Using `-r` results in `bake firmware` stuck at `Updating base firmware image with Erlang release...` step:
```
...
==> The release for helloworld-0.0.1 has been removed.
Building release with MIX_ENV=dev.
==> Modifying release for Nerves System rpi2-0.4.0-rc1
==> The release for helloworld-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/helloworld/bin/helloworld console`
Updating base firmware image with Erlang release...
```
After investigation, it looked like `cp` command froze while trying to copy pipes from this folder:
```
gmile@Eugenes-MacBook-Pro-2 ~/p/n/helloworld> ls -lat rel/helloworld/tmp/erl_pipes/helloworld
total 0
prw-r--r--  1 gmile  staff    0 Mar  5 13:40 erlang.pipe.1.r
prw-r--r--  1 gmile  staff    0 Mar  5 13:40 erlang.pipe.1.w
drwxr-xr-x  4 …
```

Use -R when copying files

---

board/nerves-common/rootfs-additions/etc/erl_inetrc

The Inet configuration was not configured to monitor the /etc/resolv.conf file properly.

Fix :nxdomain for dns resolver

---

nerves_env.exs

instead of referencing an env var with rebar in the key I added a new one which currently points to the same place as the `REBAR_PLT_DIR`. Also added the location to the system_libs instead of trying to resolve it externally.

update env vars for distillery

---

scripts/mksystem.sh

Gather the version number for debug from the `VERSION` file instead of the git tag so the build can be completed when being performed from elsewhere.
Fixes #82

Allow mksystem.sh outside of git

---

patches/buildroot/0013-raspberrypi-combined-update.patch

This includes a kernel bump to 4.4.43 and bumps for rpi-userland and
rpi-firmware. Most importantly, kernels no longer need to be marked that
use device tree, so the kernel marking logic has been removed. This will
break systems, but those systems should upgrade their kernels to avoid
any mismatches between kernel patches and rpi-firmware.

Pull in all Raspberry Pi related patches from upstream

---

patches/buildroot/0005-Add-customizable-linux-logo.patch

Fixes the following error
```
convert "/nerves/env/my_custom_system/assets/images/logo.ppm" -dither None -colors 224 -compress none /nerves/build/build/customlogo/logo_linux_clut224.ppm)
/bin/bash: -c: line 0: syntax error near unexpected token `)'
```

fix custom logo convert command dangling paren

---

scripts/merge-squashfs

The case implementation broke when adding the `sudo' buildroot package, when a folder had permission is drwx--x--x. 
This awk implementation works.

replace permissions case implementation with awk

---

scripts/merge-squashfs

Reverts nerves-project/nerves_system_br#97
The following strings do not work:
`-rwsr-xr-x` should be "4755" but I get "655"
`-rws--x--x` should be "4711" but I get "611"
`-rwxrwxrwt` should be "1777" but I get "776"
Looking at the patch again, it's more obvious that the special bits aren't handled. Therefore, I need to revert it for now.

Revert "replace permissions case implementation with awk"

---

README.md

Ubuntu Server 16.04 doesn't come with python installed, so needs to be made explicit. I am not sure about CentOS/RHEL, but doesn't hurt to add it.

Add python to dependencies

---

mix.exs
nerves.exs

`String.strip` was deprecated in favor of `String.trim`

Update for Elixir 1.5

---

create-build.sh

This let's the rest of Nerves download files to it as well so that
everyone can share their tarballs.
I added a warning for power users so they aren't surprised (much) by
this change.

Change the download directory to ~/.nerves/dl

---

patches/buildroot/0012-Raspberry-Pi-Zero-W-combined-update.patch

These both magically changed even though their tarball's contents stayed
the same. Presumably Github changed their tar.gz compression settings.
This fixes #109.

Update rpi-userland and rpi-firmware SHAs

---

create-build.sh

This enables us to use that patches directory as a global patch
directory for Buildroot. This means that we can keep some patches as
regular patches rather than patches to Buildroot.

create-build.sh: only use patches/buildroot

---

nerves-env.sh

While most people don't use nerves-env.sh, for the ones that do, knowing
the Elixir version is helpful. This calls elixir to get its version
rather than trying to derive it. The script to derive it only worked
if you manually built Elixir.

Make Elixir version printout more robust

---

patches/buildroot/0010-erlang-bump-to-otp-20.2.1.patch

This switches the upstream source to Github which has a side benefit of
working around the wget 1.19.2 auto-decompress on download issue. More
importantly, it brings in several fixes from 20.1 and adds support for
using ssh-agent to supply login credentials.

erlang: bump to version 20.2.1 

---

package/nbtty/nbtty.hash
package/nbtty/nbtty.mk

This reduces ANSI escape sequence traffic over the serial port to make things print a little faster especially when dumping logs.

nbtty: bump to v0.3.2

---

patches/buildroot/0010-erlang-bump-to-otp-20.3.1.patch

This fixes a regression in 20.3.1 with the ssl application.

erlang: bump to 20.3.1

---

patches/buildroot/0010-erlang-bump-to-otp-20.3.2.patch
patches/buildroot/0011-linux-add-BR2_LINUX_KERNEL_NEEDS_HOST_LIBELF.patch
patches/buildroot/0011-rpi-firmware-support-kernel-selection.patch
patches/buildroot/0012-linux-fix-passing-of-host-CFLAGS-and-LDFLAGS.patch
patches/buildroot/0013-rpi-firmware-support-kernel-selection.patch
patches/buildroot/0014-rpi-firmware-support-rpi-b-plus.patch
patches/buildroot/0015-package-rpi-firmware-improve-installation-of-dtb-fil.patch
patches/buildroot/0016-package-rpi-bt-firmware-change-to-LibreELEC-github-r.patch
patches/buildroot/0017-package-rpi-wifi-firmware-change-to-LibreELEC-github.patch

This pulls in support for the Linux 4.9 kernel on the Raspberry Pi and includes updated firmware files for the Raspberry Pi 3 B+'s WiFi and BT modules.
It also includes a patch to Erlang that I ran into while doing this work.

Support the Raspberry Pi 3 B+

---

nerves_env.exs
scripts/nerves-env-helper.sh

They were pointing to host pkg_config directories which would get the
wrong header files and libraries. I don't know how this ever worked

Point PKG_CONFIG environment variables to staging

---

patches/buildroot/0010-erlang-bump-to-otp-20.3.5.patch

Patch Package:           OTP 20.3.5
Git Tag:                 OTP-20.3.5
Date:                    2018-05-03
Trouble Report Id:       OTP-15034, OTP-15050
Seq num:
System:                  OTP
Release:                 20
Application:             erts-9.3.1, ssl-8.2.6
Predecessor:             OTP 20.3.4
Check out the git tag OTP-20.3.5, and build a full OTP system
including documentation. Apply one or more applications from this
build as patches to your installation using the 'otp_patch_apply'
tool. For information on install requirements, see descriptions for
each application version below.
--- erts-9.3.1 ------------------------------------------------------
--------------------------------------------------------------- …

erlang: bump to 20.3.5

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This adds bulletproofing against whitespace creeping into hostnames.

erlinit: bump to v1.4.1

---

support/docker/nerves/Dockerfile

I didn't test this, but I assume that it would be good to keep the versions in this file up-to-date?

Dockerfile: bump OTP to 20.3 and fwup to 1.1.0

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This removes the need for every system to duplicate its U-boot
environment parameters in erlinit.config. In other words, boardid reads
/etc/fw_env.config now.

boardid: bump to v1.1.0

---

patches/buildroot/0009-fwup-bump-to-v1.2.0.patch

This adds meta-uuid so that systems can track a unique ID for what was
actually installed.

fwup: bump to v1.2.0

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This addresses an issue with using empty U-Boot environment variables.
An empty `serial_number` won't be used to supply a board's ID.

boardid: bump to v1.1.1

---

patches/buildroot/0009-fwup-bump-to-v1.2.1.patch

This version adds some bulletproofing and additional regression tests to
meta-uuid. It also adds support for ${FWUP_META_UUID} so that the UUID
can be referenced in fwup.conf scripts. This is needed to support saving
the UUID to the Nerves.Runtime.KV metadata so that it can be accessed by
firmware update libraries.

fwup: bump to v1.2.1

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This pulls in an update to the filesystem mount calls that fixes
a parse error from Docker.

erlinit: bump to v1.4.2

---

package/nbtty/nbtty.hash
package/nbtty/nbtty.mk

This pulls in a fix for process exits not being detected and support for
retrying tty files so that progress can be made on configfs/USB gadget
work.

nbtty: bump to v0.4.0

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This pulls in the signal mask fix. This fixes an issue where nbtty was
waiting for SIGCHLD, but would not receive it since it inherited
erlinit's signal mask. The signal mask is restored to the default before
launching applications now so that applications don't need to force
their signal masks.

erlinit: bump to v1.4.4

---

package/nerves-config/Config.in
package/nerves-config/nerves-config.mk

This change makes rng-tools a require dependency for all Nerves systems
and results in two ~16 KB binaries being installed. One is `rngd` and
the other is `rngtest`.
The `rngd` program transfers random data from hardware generators to the
Linux kernel. This is very important since the getrandom() syscall can
hang programs for 5 minutes at boot while the kernel accumulates
entropy. The hardware random number generators can get the kernel going
very quickly.
This issue has become more prevalent due to C libraries, the Linux
kernel and applications getting better with how they gather their
cryptographic random data and using cryptographic random number for more
things.

Add rng-tools to all Nerves systems

---

nerves-env.sh

This is more useful than just printing the crosscompiler prefix for
those of us who use this script.

Print the gcc version

---

board/nerves-common/post-createfs.sh
nerves_env.exs
scripts/nerves-env-helper.sh

This saves the mkspecs directory to staging so that it gets distributed
with systems and then sets the QMAKESPECS environment variable for
builds. `qmake` will look at the variable to know how to build Qt-based
projects.

Support Qt/QMake projects

---

support/docker/nerves_system_br/Dockerfile
support/docker/nerves_system_br/docker-entrypoint.sh

When running the docker image, we set the user and group ids to those of the user from the host. This fixes permissions issues that arise from writing files back to the host from within the container. Unfortunately since this user and group do not actually exist, it can cause some bad behavior with packages in buildroot. In the example case, `host-ncurses`. This will set the entrypoint and create and switch users if the values were passed through in the `--env`

Create and switch user in docker entrypoint if one was set

---

patches/buildroot/0014-ncurses-disable-terminfo-database-install-for-host-n.patch

This fixes the root cause of the home directory right. We previously
worked around this issue by creating a home directory in the Docker
configurations. That fix is no longer necessary with this change.

Disable the ncurses write to the user's home directory

---

patches/buildroot/0009-erlang-bump-to-21.0.patch

--- POTENTIAL INCOMPATIBILITIES -------------------------------------
OTP-15225    Application(s): erts
Fixed a bug causing some Erlang references to be
inconsistently ordered. This could for example cause
failure to look up certain elements with references as
keys in search data structures. This bug was introduced
in R13B02.
Thanks to Simon Cornish for finding the bug and
supplying a fix.
--- compiler-7.2.3 --------------------------------------------------
The compiler-7.2.3 application can be applied …

erlang: bump to 21.0.5

---

patches/buildroot/0015-erlang-make-OTP-version-configurable.patch

This adds support for OTP 20 back so that users who cannot upgrade to
OTP 21 can still follow along with the latest patches and security
updates.
The default remains OTP 21. OTP 20 must be explicitly chosen.

erlang: continue to support OTP 20 systems

---

patches/buildroot/0016-qt5-bump-latest-version-to-5.11.0.patch
patches/buildroot/0017-qt5-bump-latest-version-to-5.11.1.patch

This pulls in the upstream patches to bump to 5.11.0 and then 5.11.1.
The next Buildroot release will remove both.

qt5: bump to 5.11.1

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This also adds a hash for the LICENSE file for 'make legal-info'.

erlinit: bump to v1.4.6

---

support/docker/nerves_system_br/Dockerfile
support/docker/nerves_system_br/docker-entrypoint.sh

Trying to accomplish the following
1. Fix an issue with docker running on linux hosts where it would raise an exception that the group id for 1000 does not exist. This is an issue in the docker-entrypoint script. The PR adds the group before trying to add the user to it.
2. Improve docker image layer caching. Since fwup changes more frequently then the reset of the host packages, I am splitting it out in an attempt to see if it can reuse the other layers. I am hoping that this shrinks an 800mb download on every bump to roughly the size of fwup. 
3. Add `libmnl-dev` for building nerves project apps using this image.

Docker image updates

---

scripts/scrub-otp-release.sh

This adds the most common reasons that I get scrubber errors. Sourcing
nerves-env.sh seems like it should be an unlikely cause anymore.

Improve scrubber error message

---

support/docker/nerves_system_br/Dockerfile
support/docker/nerves_system_br/docker-entrypoint.sh

use `-o` to fix issues with setting groups that already exist `groupadd: GID '20' already exists`

Set the group and user even if it exists

---

scripts/merge-squashfs

Piping multiple sed calls together can result in extreme slowness on some systems.  However, the same result can be accomplished more efficiently by using a single call to sed with multiple scripts passed in (see https://www.gnu.org/software/sed/manual/sed.html#Multiple-commands-syntax)
This change reduced `mix firmware` runtime from 30+ minutes to < 2 minutes on my system (MacOS High Sierra 10.13.6).

Use single sed call with multiple -e's

---

package/nerves_heart/nerves_heart.hash
package/nerves_heart/nerves_heart.mk

This changes logging to write to the kernel log buffer if it's available
so that heart output isn't lost with Nerves. It also merges in an
upstream fix.

nerves_heart: bump to v0.2.0

---

patches/buildroot/0009-rpi-firmware-support-kernel-selection.patch
patches/buildroot/0010-erlang-switch-to-Github.patch
patches/buildroot/0011-erlang-run-autoconf-via-otp_build.patch
patches/buildroot/0012-erlang-support-version-selection.patch
patches/buildroot/0013-erlang-bump-to-21.0.8.patch

The refactoring of the patches breaks the erlang changes into finer
grain commits to make it easier to maintain. Bumping the version was
getting painful in terms of rebasing conflicts. This makes it easier and
also makes it more possible to push our Erlang patches upstream.

erlang: refactor patches and bump to 21.0.8

---

patches/buildroot/0013-erlang-bump-to-21.0.9.patch

Changelog:
--- compiler-7.2.4 --------------------------------------------------
The compiler-7.2.4 application can be applied independently of other
applications on a full OTP 21 installation.
OTP-15292    Application(s): compiler
Fix a regression in OTP-15204 that removed .beam file
metadata that some external build tools relied on.
Full runtime dependencies of compiler-7.2.4: crypto-3.6, erts-9.0,
hipe-3.12, kernel-4.0, stdlib-2.5
--- erts-10.0.8 ----------------------------------------------------- …

erlang: bump to 21.0.9

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This version adds support for querying serial numbers from the ATECC508A
CryptoAuthentication device.

boardid: bump to v1.2.0

---

patches/buildroot/0009-rpi-firmware-support-kernel-selection.patch

This fixes an issue with the RPi0's gadget USB port being flaky with the
new RPi0 4.14.71 build. It may fix other issues.

rpi-firmware: add firmware for Linux 4.14.71

---

patches/buildroot/0014-fwup-bump-to-v1.2.6.patch

The difference between 1.2.5 and 1.2.6 shouldn't affect Nerves. The
changes were to fix a compiler error that doesn't affect Nerves, to fix
a bug on OSX, and improve a couple issues in shell scripts.
This patch isn't included in the existing fwup version patch since that
one has been accepted to Buildroot and will disappear on the next BR
update.

fwup: bump to v1.2.6

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This fixes an issue with detecting root disks on NVME-connected drives.

erlinit: bump to v1.4.7

---

scripts/scrub-otp-release.sh

It turns out that `readelf` fails on OSX executables so there was a
regression on being able to detect them in releases. This changes the
logic so that `readelf` is tried first. It gives the most reliable
information. If `readelf` fails, then there's likely something wrong if
the file isn't a shell script. This uses `file` to figure that out and
guesses if x86_64 is in the output or "shared library" that something is
wrong. Everything else is assumed to be ok. Note that x86_64 is checked
after the readelf check so even on x86_64 devices, this check should be
ok.
Here's a sample of the error for a bad executable:
```
scrub-otp-release.sh: ERROR: Unexpected executable format for 'curl'
Got:
file:Mach-O 64-bit executable x86_64
Expecting:
readelf:ARM;0x5000200, Version5 EABI, soft-float ABI …
```

Fix scrubber missing OSX executables

---

package/nbtty/nbtty.hash
package/nbtty/nbtty.mk

This adds an option to disable output to the tty until the user presses
the enter key. This reduces I/O when no one is paying attention and can
remove the random output on the USB gadget tty on initial connect.

nbtty: bump to v0.4.1

---

scripts/scrub-otp-release.sh

Since the scrubber rules were last edited, Windows Powershell scripts
started being generated. Those are obviously not useful for Nerves so
delete them. Also remove the .script files that are the source for the
.boot files.
On a simple project this seems to save ~50 KB compressed and ~25 extra
files.

Scrupt Powershell scripts and .script files

---

patches/buildroot/0013-erlang-bump-to-21.1.3.patch

This is the only change:
```
OTP-15430    Application(s): erts
Related Id(s): ERIERL-237
Added an optional ./configure flag to compile the
emulator with spectre mitigation:
--with-spectre-mitigation
Note that this requires a recent version of GCC with
support for spectre mitigation and the
--mindirect-branch=thunk flag, such as 8.1.
```

erlang: bump to 21.1.3

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This release improves ATECC508A support and adds an option to force the
ID when all other options fail. I'm using this in manufacturing to make
it easy to connect to unprovisioned devices.

boardid: v1.3.0

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This adds support for reading a NervesKey serial number from the OTP
memory in it. This serial number is programmed at manufacture time and
can't be modified.

boardid: bump to v1.4.0

---

patches/buildroot/0014-libopenssl-bump-version-to-1.1.0h.patch

This pulls in a pending patch in Buildroot to update the version of
OpenSSL from 1.0.2 to 1.1.0h. This fixes what appears to be issues with
Erlang using OpenSSL engines. It also enables Erlang crypto features
like additional algorithms.
OpenSSL 1.0.2 is also feeling dated now. The OpenSSL project has
indicated that they'll stop supporting it after 2019.

openssl: bump to 1.1.0h

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This add supports for reading boardid options from /etc/boardid.config
rather than having to copy them around in the erlinit.config. It is
backwards compatible and requires no changes to existing Nerves systems.

boardid: bump to v1.5.0

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This fixes issues where it was possible to set the hostname to invalid
strings and have things break in weird to debug ways.

erlinit: bump to v1.4.8

---

scripts/scrub-target.sh

This utilities are small, and run_erl is quite useful for logging the
console once the next release of erlinit is integrated.

Don't scrub run_erl and to_erl

---

patches/buildroot/0008-rpi-firmware-support-kernel-selection.patch

This aligns nerves_system_br with upstream Buildroot for rpi-firmware
versions.

rpi-firmware: remove patch holding back version

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This fixes an issue that was preventing log messages to be recorded when
verbose is enabled due to a rate limiter in the kernel. It also makes it
possible to start Erlang with `run_erl`.

erlinit: v1.4.9

---

patches/buildroot/0012-erlang-bump-to-21.2.2.patch

See http://erlang.org/download/OTP-21.2.1.README and
http://erlang.org/download/OTP-21.2.2.README for fixes.

erlang: bump to 21.2.2

---

scripts/scrub-otp-release.sh

This doesn't work. Path dependencies always build and put their build
products in their directory, so you always have to "mix clean" on those
when switching devices.

Fix advice for using "build_embedded"

---

board/nerves-common/rootfs_overlay/etc/erl_inetrc

This fixes some comments from when this file was less understood.
An important change is to remove the fallback to the system resolver
when Erlang's resolver returns an error. This fallback isn't needed and
only delayed the inevitable DNS failure response.

Document /etc/erl_inetrc contents

---

patches/buildroot/0012-erlang-bump-to-21.2.4.patch

See http://erlang.org/download/OTP-21.2.3.README and
http://erlang.org/download/OTP-21.2.4.README for fixes.

erlang: bump to 21.2.4

---

patches/buildroot/0015-erlang-don-t-build-host-erlang-for-Nerves.patch

This saves minutes of build time and is unneeded for Nerves since Erlang
source code is compiled outside of Buildroot.

Disable host-erlang since unneeded

---

scripts/nerves-env-helper.sh

The asdf shims break the logic for figuring out the OTP minor version.
This change fixes it by determining the path to the OTP_VERSION file
inside of Erlang. If that fails, then fall back to just using the major
number of telling the user that the minor versions might be different.

Fix OTP minor version detection for asdf

---

scripts/rel2fw.sh

There are a couple reasons I think this location should be moved to `_build`. My favorite one would probably be the git surprises that can occur at the same time as calling `mix firmware`.

Move build tmp dir to _build

---

patches/buildroot/0013-fwup-bump-to-v1.3.1.patch

This also removes the `img2fwup` script from being installed to
`/usr/bin`.

fwup: bump to 1.3.1

---

patches/buildroot/0015-erlang-enable-deterministic-compile-flag.patch

This makes builds slightly more deterministic by removing many absolute paths from the core Erlang libraries. (Saves 60KB after compression in helloworld app)
From the Erlang compiler docs:
>Omit the options and source tuples in the list returned by Module:module_info(compile), and reduce the paths in stack traces to the module name alone. This option will make it easier to achieve reproducible builds. 
Before:
```elixir
iex> :kernel.module_info()
[
module: :kernel,
exports: [
start: 2,
stop: 1,
config_change: 3,
init: 1,
module_info: 0,
module_info: 1
],
attributes: [
vsn: [224767665711555302789215303007070581728],
behaviour: [:supervisor]
],
compile: [
version: '7.3.1',
options: [
:debug_info,
{:i,
'/home/fhunleth/nerves/nerves_system_br/o/rpi0/build/erlang-21.2.7/lib/kernel/src/../inclu …
```

erlang: enable deterministic build flag

---

patches/buildroot/0012-erlang-support-OTP-20-21-and-22.patch

See release notes at:
http://erlang.org/pipermail/erlang-questions/2019-June/098024.html

erlang: bump to 22.0.2

---

patches/buildroot/0012-erlang-support-OTP-20-21-and-22.patch

This bumps all Erlang versions for each OTP release to their latest
patch levels.

erlang: bump to 20.3.8.9, 21.3.8.4 and 22.0.4

---

patches/buildroot/0012-erlang-support-OTP-20-21-and-22.patch

This bumps the OTP 20 and OTP 21 versions to their latest patch levels.

erlang: bump to 20.3.8.9 and 21.3.8.4

---

patches/buildroot/0018-qt5-bump-to-5.13.0.patch

This fixes webengine compilation errors on x86_64. Unfortunately, it
doesn't fix errors on Raspberry Pi builds.
See https://github.com/nerves-project/nerves_system_br/pull/337.
This is a squashed, rebased, and git-patch-ified version of the above
PR.

qt5: bump to 5.13.0

---

support/docker/nerves_system_br/Dockerfile

The latest version of buildroot seems to require gawk to be present on the host

Add gawk to the docker image

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch
support/docker/nerves_system_br/Dockerfile

Erlang/OTP 22.0.7 release announcement:
http://erlang.org/pipermail/erlang-questions/2019-July/098183.html
Erlang/OTP 22.0.6 release announcement:
http://erlang.org/pipermail/erlang-questions/2019-July/098173.html

erlang: bump to 22.0.7

---

support/docker/nerves_system_br/Dockerfile

`jq` is used a lot in system builds. This adds it to the image that we use on CI.

Add jq to the Dockerfile

---

nerves_env.exs
scripts/nerves-env-helper.sh

This adds support for elixir_make projects that run `pkg-config` to find
include and library paths in Nerves systems.

Set pkg-config environment

---

patches/buildroot/0017-rpi-firmware-support-kernel-selection.patch

This fixes an error from vc_dispmanx_display_open. See
https://github.com/fhunleth/rpi_fb_capture/issues/2 for details.

rpi-firmware: bump to 38e81f2

---

support/docker/nerves_system_br/Dockerfile

pkg-config is useful for vintage_net. I added vim-tiny since not having vi on CircleCI when debugging builds is really annoying.

Dockerfile: add pkg-config and vim-tiny

---

scripts/scrub-otp-release.sh

This attempts to help people updating to Nerves 1.5 who didn't see the
release notes. If you don't do anything to a project when you update,
the build machine's OTP libraries get included. The scrubber detects
this. The error message didn't say that this was an issue. I removed the
Nerves 1.3 error help since that feels like it has served its duty.

Update scrubber error since Nerves 1.5 causes it

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This fixes an issue where zombie processes could be created faster than
erlinit could clean them up and then erlinit would stop cleaning them
up.

erlinit: bump to v1.5.1

---

scripts/mksystem.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/mksystem.sh 
In scripts/mksystem.sh line 27:
if [ -z $ARCHIVE_NAME ]; then
In scripts/mksystem.sh line 33:
if [ ! -f $PWD/package/pkg-generic.mk ]; then
In scripts/mksystem.sh line 39:
if [ -z $BASE_DIR ]; then
In scripts/mksystem.sh line 44:
NERVES_DEFCONFIG=$(grep BR2_DEFCONFIG= $BASE_DIR/.config | sed -e 's/BR2_DEFCONFIG=".*\/\(.*\)"/\1/')
In scripts/mksystem.sh line 47:
rm -fr $WORK_DIR
In …
```

Fix mksystem shellcheck warnings

---

scripts/rel2fw.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/rel2fw.sh 
In scripts/rel2fw.sh line 80:
shift $(($OPTIND-1))
^-- SC2004: $/${} is unnecessary on arithmetic variables.
```
Fixes above warning.
https://github.com/koalaman/shellcheck/wiki/SC2004

Fix rel2fw shellcheck warnings

---

scripts/download-buildroot.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/download-buildroot.sh 
In scripts/download-buildroot.sh line 34:
rm -fr $EXTRACTED_DIRNAME $BUILDROOT_PATH
In scripts/download-buildroot.sh line 51:
pushd $DL
In scripts/download-buildroot.sh line 52:
if ! wget $DOWNLOAD_URL; then
In scripts/download-buildroot.sh line 55:
if ! wget $ALTERNATIVE_URL; then
In scripts/download-buildroot.sh line 66:
mkdir -p $EXTRACTED_DIRNAME
^-- SC2086: Double quote …
```

Shellcheck download-buildroot.sh fixes

---

scripts/mksyslinuxfs.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/mksyslinuxfs.sh 
In scripts/mksyslinuxfs.sh line 37:
rm -f $BOOTPART
In scripts/mksyslinuxfs.sh line 38:
dd if=/dev/zero of=$BOOTPART count=0 seek=$BOOTSIZE 2>/dev/null
In scripts/mksyslinuxfs.sh line 39:
$MKFS_VFAT -F 12 -n BOOT $BOOTPART >/dev/null
In scripts/mksyslinuxfs.sh line 40:
$SYSLINUX -i $BOOTPART
```
Fixes above warnings.

Fix mksyslinuxfs shellcheck warnings

---

scripts/scrub-target.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/scrub-target.sh 
In scripts/scrub-target.sh line 73:
echo '  BR2_ROOTFS_SKELETON_CUSTOM_PATH="${BR2_EXTERNAL_NERVES_PATH}/board/nerves-common/skeleton"'
^-- SC2016: Expressions don't expand in single quotes, use double quotes for that.
```
https://github.com/koalaman/shellcheck/wiki/SC2016

Fix scrub-target shellcheck warning

---

scripts/ci-build.sh

```
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/ci-build.sh 
In scripts/ci-build.sh line 22:
cd ci
^-- SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
In scripts/ci-build.sh line 25:
../create-build.sh ../configs/${CI_DEFCONFIG_DIR}/${CI_DEFCONFIG}_defconfig out || exit 1
```
Fixes these two warnings.

Fix ci-build.sh shellcheck warnings

---

scripts/buildroot-state.sh

```
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/buildroot-state.sh 
In scripts/buildroot-state.sh line 36:
pushd $BR_PATCH_DIR >/dev/null
```

Fix shellcheck buildroot-state warnings

---

support/docker/nerves_system_br/docker-entrypoint.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck support/docker/nerves_system_br/docker-entrypoint.sh 
In support/docker/nerves_system_br/docker-entrypoint.sh line 9:
groupadd -o -g $GID nerves
In support/docker/nerves_system_br/docker-entrypoint.sh line 10:
useradd -o -g $GID -u $UID -m nerves
In support/docker/nerves_system_br/docker-entrypoint.sh line 14:
gosu nerves $@
^-- SC2068: Double quote array expansions to avoid re-splitting elements.
```

Fix shellcheck docker-entrypoint warnings

---

scripts/nerves-env-helper.sh

```
In scripts/nerves-env-helper.sh line 33:
ALL_CROSSCOMPILE=$(ls "$NERVES_TOOLCHAIN"/usr/bin/*gcc | sed -e s/-gcc//)
^-- SC2012: Use find instead of ls to better handle non-alphanumeric filenames.
In scripts/nerves-env-helper.sh line 50:
ALL_CROSSCOMPILE=$(ls "$NERVES_TOOLCHAIN"/bin/*gcc | sed -e s/-gcc//)
^-- SC2012: Use find instead of ls to better handle non-alphanumeric filenames.
In scripts/nerves-env-helper.sh line 119:
export REBAR_TARGET_ARCH="$(basename "$CROSSCOMPILE")"
^-- SC2155: Declare and assign separately to avoid masking return values.
```

Fix nerves-env-helper shellcheck warnings

---

scripts/ci-deploy.sh

```bash
λ  ~/code/nerves/nerves_system_br (master)  $ shellcheck scripts/ci-deploy.sh 
In scripts/ci-deploy.sh line 41:
WORK_DIR=_build/*/nerves/system
^-- SC2125: Brace expansions and globs are literal in assignments. Quote it or use an array.
In scripts/ci-deploy.sh line 43:
WORK_DIR=.nerves/artifacts/*
^-- SC2125: Brace expansions and globs are literal in assignments. Quote it or use an array.
In scripts/ci-deploy.sh line 46:
cp $WORK_DIR/${CI_SYSTEM_NAME}.tar.gz artifacts/$ARTIFACT_SUBDIR/${CI_SYSTEM_NAME}-$BRANCH_OR_TAG.tar.gz …
```

Fix shellcheck ci-deploy warnings

---

scripts/ci-deploy.sh
scripts/mksystem.sh

A few shellcheck fixes broke wildcard expansions. This works around this
issues.

Fix quote expansion

---

support/docker/nerves_system_br/Dockerfile

Fixes build issues resulting in the error 
```
ModuleNotFoundError: No module named 'distutils.sysconfig'
configure: error: Python failed to run; see above error.
```

Add python3-distutils to docker image

---

patches/buildroot/0014-qt5-bump-to-5.13.0.patch

`getconf NAME_MAX /` returns 242 on CircleCI rather than 255. This
adjusts the patch for building Chromium to this shorter length.

qt5webengine: Reduce path len to fix CircleCI error

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

[From the release notes]
Erlang/OTP 22.1 is the first service release for the 22 major release
with new features, improvements as well as bugfixes
Potential Incompatibilities
* Mnesia: Transactions with sticky locks could with async_asym
transactions be committed in the wrong order, since asym transactions
are spawned on the remote nodes. To fix this bug the communication
protocol between mnesia nodes had to be updated, thus mnesia will no
longer be able to connect to nodes earlier than mnesia-4.14 , OTP-19.0.
* Stdlib: Debugging of time-outs in gen_statem has been improved.
Starting a time-out is now logged in sys:log and sys:trace. Running
time-outs are visible in server crash logs, and with sys:get_status. Due
to this system events {start_timer, Action, State} and {insert_timout, …

erlang: bump to OTP 22.1

---

package/bborg-overlays/bborg-overlays.hash
package/bborg-overlays/bborg-overlays.mk

See
https://github.com/beagleboard/bb.org-overlays/compare/f3d81bb934b1be9f532e31101b2e3f54b4488f14...8e155ff1cdb02298d735c8a14dd152a1e884f3d7
for changes.

bborg-overlays: bump the latest git hash

---

patches/buildroot/0016-package-wpa_supplicant-security-bump-version-to-2.9.patch
patches/buildroot/0017-package-wpa_supplicant-add-Config.in-option-for-WPA3.patch
patches/buildroot/0018-package-wpa_supplicant-fix-AP-mode-settings.patch

This brings in upstream patches to advance the wpa_supplicant to v2.9.
This fixes a Linux kernel module crash when using enterprise WiFi on
Raspberry Pi WiFi modules.
```
00:04:07.122 [warn]  ------------[ cut here ]------------
00:04:07.122 [warn]  WARNING: CPU: 2 PID: 319 at drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.c:5126 brcmf_cfg80211_set_pmk+0x40/0x50 [brcmfmac]
00:04:07.135 [warn]  Modules linked in: fixed brcmfmac sha256_generic cfg80211 brcmutil snd_bcm2835(C) snd_pcm snd_timer snd bcm2835_v4l2(C) videobuf2_vmalloc videobuf2_memops v4l2_common bcm2835_mmal_vchiq(C) videobuf2_v4l2 videobuf2_common videodev media vc_sm_cma(C) dwc2
00:04:07.135 [warn]  CPU: 2 PID: 319 Comm: wpa_supplicant Tainted: G        WC        4.19.75 #2
00:04:07.259 [warn]  Hardware name: …
```

wpa_supplicant: bump version to 2.9; patches

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch
support/docker/nerves_system_br/Dockerfile

OTP 22.1.5:
--- snmp-5.4.2 ------------------------------------------------------
The snmp-5.4.2 application can be applied independently of other
OTP-16207    Application(s): snmp
Related Id(s): ERIERL-427
The agent discovery process has been made to work with
snmptrapd..
Full runtime dependencies of snmp-5.4.2: crypto-3.3, erts-6.0,
kernel-3.0, mnesia-4.12, runtime_tools-1.8.14, stdlib-2.5
OTP 22.1.4: http://erlang.org/pipermail/erlang-announce/2019-October/000088.html
OTP 22.1.3: http://erlang.org/pipermail/erlang-announce/2019-October/000087.html
OTP 22.1.2: …

erlang: bump to 22.1.5

---

patches/buildroot/0012-fwup-bump-to-v1.4.0.patch
support/docker/nerves_system_br/Dockerfile

fwup v1.4.0 adds support for GPT partitions and makes it much easier to
handle UEFI-only boards.

fwup: bump to v1.4.0

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

--- compiler-7.4.8 --------------------------------------------------
The compiler-7.4.8 application can be applied independently of other
OTP-16219    Application(s): compiler, erts
Related Id(s): ERL-1076
The compiler could do an unsafe optimization of
receives, which would cause a receive to only scan part
of the message queue.
This bug fix in the compiler fixes a bug in the socket
module.
Full runtime dependencies of compiler-7.4.8: crypto-3.6, erts-9.0,
hipe-3.12, kernel-4.0, stdlib-2.5
--- …

erlang: bump to 22.1.6

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This has a fix for making [slave](http://erlang.org/doc/man/slave.html)
work with Nerves.

erlinit: bump to v1.5.3

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

From the release notes:
--- compiler-7.4.9 --------------------------------------------------
The compiler-7.4.9 application can be applied independently of other
OTP-16259    Application(s): compiler
Related Id(s): ERIERL-436
Fixed a performance bug that caused repeated matches of
large records to take a very long time to compile.
Full runtime dependencies of compiler-7.4.9: crypto-3.6, erts-9.0,
hipe-3.12, kernel-4.0, stdlib-2.5
--- erts-10.5.5 ----------------------------------------------------- …

erlang: bump to 22.1.7

---

board/nerves-common/skeleton/etc/resolv.conf

This keeps the symlink pointing inside this package and is consistent
with upstream Buildroot:
https://git.busybox.net/buildroot/tree/system/skeleton/etc/resolv.conf

Convert resolv.conf to a relative symlink

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

From the release notes:
OTP-16301    Application(s): erts
Related Id(s): ERL-1079
Large amounts of quickly executed dirty work could
cause heavy contention on an internal spin lock. The
spin lock was replaced by a mutex which behaves much
better under these conditions.

erlang: bump to 22.1.8

---

board/nerves-common/busybox-1.22.config

dmesg was inadvertently removed in
0aae2f404e3fcfe5240e941068eccd91306f8c7a. This adds it back. It's about
3K so it's an insignificant addition.

busybox: add dmesg back

---

board/nerves-common/busybox-1.22.config
patches/buildroot/0016-rpi-wifi-firmware-bump-to-BCM43430-7.45.98.83-BCM434.patch

This appears to fix an issue where the wpa_supplicant would report failures
that look like this on an RPi0 W:
```
[  368.263090] brcmfmac: brcmf_cfg80211_stop_ap: SET SSID error (-110)
[  368.265197] brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_DOWN error -110
[  368.267254] brcmfmac: brcmf_cfg80211_stop_ap: setting AP mode failed -110
[  368.269238] brcmfmac: brcmf_cfg80211_stop_ap: BRCMF_C_UP error -110
[  368.271064] brcmfmac: brcmf_vif_set_mgmt_ie: vndr ie set error : -110
[  368.272910] brcmfmac: brcmf_vif_set_mgmt_ie: vndr ie set error : -110
[  368.283320] brcmfmac: brcmf_vif_set_mgmt_ie: vndr ie set error : -512
[  368.285377] brcmfmac: brcmf_set_mpc: fail to set mpc
[  368.289559] brcmfmac: brcmf_sdio_read_control: last control frame is being processed.
[  368.300939] brcmfmac: …
```

rpi-wifi-firmware: bump to BCM43430 (7.45.98.83), BCM4345

---

patches/buildroot/0017-mesa3d-add-support-for-v3d.patch

This makes it possible to enable the v3d driver for the Raspberry Pi 4.
Video on the RPi4 is still not working for me, but I believe this is
patch is important for others to use. Since v3d support option has to be
enabled in Buildroot for it to alter a build, this is a low risk patch.

mesa3d: add support for v3d

---

board/nerves-common/device_table.txt
patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

This comments out a few directories that never are used on Nerves devices.
For example, the if-*.d directories are particularly confusing since
they're not used so putting files in there won't do anything.
To use this device_table.txt file, add or modify the following line in the
system's nerves_defconfig:
BR2_ROOTFS_DEVICE_TABLE="${BR2_EXTERNAL_NERVES_PATH}/board/nerves-common/device_table.txt"

Add Nerves-specific device_table.txt

---

Config.in
package/ply/Config.in
package/ply/ply.hash
package/ply/ply.mk

This adds the ply utility for running eBPF programs.
It requires very low level knowledge to run unfortunately, so it's not
something that will be easily accessible. To get it running, I had to:
1. Make sure it was compiled with the correct Linux headers
2. Change the following kernel options:
```
+CONFIG_BPF_SYSCALL=y
-# CONFIG_PERF_EVENTS is not set
+CONFIG_KPROBES=y
+CONFIG_FUNCTION_TRACER=y
+CONFIG_FTRACE_SYSCALLS=y
```
3. Mount debugfs at `/sys/kernel/debug`
The directions on the ply site mostly work. For the Raspberry Pi, the
Linux syscall functions start with `sys` and not `SyS` since it doesn't
use syscall wrappers like x86.

ply: new package

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

See https://erlang.org/download/OTP-22.2.1.README for details.
From the email announcement:
```
--- erts-10.6.1 -----------------------------------------------------
Note! The erts-10.6.1 application *cannot* be applied independently
of other applications on an arbitrary OTP 22 installation.
On a full OTP 22 installation, also the following runtime
dependency has to be satisfied:
-- kernel-6.5.1 (first satisfied in OTP 22.2)
OTP-16314    Application(s): erts
Related Id(s): ERL-1098
Corrected an issue with the new socket api which could
cause a core dump. A race during socket close could
cause a core dump (an invalid …
```

erlang: bump to version 22.2.1

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

See https://erlang.org/download/OTP-22.2.2.README for details.
From the release announcement:
```
--- crypto-4.6.4 ----------------------------------------------------
The crypto-4.6.4 application can be applied independently of other
OTP-16376    Application(s): crypto, ssh
Constant time comparisons added.
Full runtime dependencies of crypto-4.6.4: erts-9.0, kernel-5.3,
stdlib-3.4
--- erts-10.6.2 ----------------------------------------------------- …
```

erlang: bump to 22.2.2

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This version adds support for getting serial numbers from SMBIOS/DMI on
x86 systems.

boardid: bump to v1.6.0

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch
support/docker/nerves_system_br/Dockerfile

See https://erlang.org/download/OTP-22.2.3.README for details.
From the release announcement:
```
--- compiler-7.5.1 --------------------------------------------------
The compiler-7.5.1 application can be applied independently of other
OTP-16385    Application(s): compiler
Related Id(s): ERL-1128
Fixed a bug in the compiler that could cause it to
reject valid code.
Full runtime dependencies of compiler-7.5.1: crypto-3.6, erts-9.0,
hipe-3.12, kernel-4.0, stdlib-2.5
--- ssl-9.5.2 …
```

erlang: bump to 22.2.3

---

package/edk2/edk2.mk

This fixes an issue where the `efi-part` directory hasn't been created
so the shell gets renamed as `efi-part`. Since `shell.efi` doesn't get
put in the root of the EFI system partition anyway, I moved it to the
root of the images directory and scripts can put it where ever makes
sense.

edk2: copy shell to $BINARIES_DIR

---

package/boardid/Config.in
package/boardid/boardid.hash
package/boardid/boardid.mk

This update pulls in support for hardcoding prefixes to serial numbers.
This is used in scenarios where IDs come from third party sources and
company policies requires some prefix for them to be re-used.

boardid: bump to v1.7.0

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch
patches/buildroot/0018-rng-tools-make-jitterentropy-optional.patch
support/docker/nerves_system_br/Dockerfile

See https://erlang.org/download/OTP-22.2.4.README for details.
From the release announcement:
```
--- ssl-9.5.3 -------------------------------------------------------
The ssl-9.5.3 application can be applied independently of other
OTP-16413    Application(s): ssl
Related Id(s): ERL-1136
Enhance error handling, all ALERTS shall be handled
gracefully and not cause a crash.
OTP-16424    Application(s): ssl
Enhance alert logging, in some places the role
indication of the alert origin was missing. So the log
would say undefined instead of client or server.
OTP-16426 …
```

erlang: bump to 22.2.4

---

patches/buildroot/0018-rng-tools-make-jitterentropy-optional.patch

This fixes warning prints and their associated boot delays on Raspberry
Pi Zero and other systems. Specifically, the following is printed on the
console:
```
JITTER rng fails with code 2
Failed to init entropy source jitter
```
See https://bugs.busybox.net/show_bug.cgi?id=12511 for discussion.  For
the official Nerves systems, having Jitterentropy being enabled or
disabled at compile time is reasonable since it's easy to tell whether
it's in use at all. For example, it just doesn't work on the Raspberry
Pi Zero. It does work on the BBB, but there's also hardware
acceleration, so it's not really necessary (assuming the hwrng is
trustworthy, but then if it's not, do you trust jitterentropy...).

rng-tools: make jitterentropy optional

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch

See https://erlang.org/download/OTP-22.2.5.README and
https://erlang.org/download/OTP-22.2.6.README for details.
From the release announcements:
```
--- erts-10.6.3 -----------------------------------------------------
Note! The erts-10.6.3 application *cannot* be applied independently
of other applications on an arbitrary OTP 22 installation.
On a full OTP 22 installation, also the following runtime
dependency has to be satisfied:
-- kernel-6.5.1 (first satisfied in OTP 22.2)
OTP-16436    Application(s): erts
Related Id(s): ERL-1152
A process could end up in a state where it got
endlessly rescheduled without making …
```

erlang: bump to 22.2.6

---

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch
support/docker/nerves_system_br/Dockerfile

See https://erlang.org/download/OTP-22.2.7.README and
https://erlang.org/download/OTP-22.2.8.README for details.
From the release announcements:
```
--- compiler-7.5.2 --------------------------------------------------
The compiler-7.5.2 application can be applied independently of other
OTP-16452    Application(s): compiler
Related Id(s): ERL-1161
Fixed a bug that could cause the compiler to reject
valid code that used the is_map_key/2 BIF.
OTP-16456    Application(s): compiler
Related Id(s): ERL-1163
Fixed a bug that could cause the compiler to reject
valid code that …
```

erlang: bump to 22.2.8

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This adds support for the nVidia Jetson Nano and similar boards.

boardid: bump to v1.8.0

---

patches/buildroot/0016-rpi-firmware-bump-to-1.20200212.patch

Bump to the latest released rpi-firmware version so that its at the same
level as the upcoming v1.11.0 nerves_system_rpi* Linux kernel versions.

rpi-firmware: bump to 1.20200212

---

support/docker/nerves_system_br/Dockerfile

Bump the version of Erlang/OTP to 22.2.8 now that Erlang Solutions has
it posted.

Dockerfile: bump erlang to 22.2.8

---

patches/buildroot/0010-erlang-support-OTP-20-21-and-22.patch
support/docker/nerves_system_br/Dockerfile

See https://erlang.org/download/OTP-22.3.README for details.
Highlights:
```
OTP-15856    Application(s): ssl
Implementation of the key and initialization vector
update feature, and general hardening of TLS 1.3.
There are cryptographic limits on the amount of
plaintext which can be safely encrypted under a given
set of keys.
This change enforces those limits by triggering
automatic key updates on TLS 1.3 connections.
OTP-16253    Application(s): ssl
Add support for TLS 1.3 Session Tickets (stateful and
stateless). This allows session resumption using keying
material from a previous successful handshake.
OTP-16309    Application(s): erts, sasl
A socket "registry" has been added making it possible
to list current open sockets.
OTP-16485    Application(s): ssh
The new functions …
```

erlang: bump to 22.3

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This update fixes an issue with rootdisk symlink creation on a few
platforms. This did not affect any of the officially supported Nerves
systems.

erlinit: bump to v1.6.1

---

board/nerves-common/skeleton/etc/protocols

getprotobyname(3) is a C library call that scans `/etc/protocols` to
find the protocol number. If a program uses getprotobyname(3), and
`/etc/protocols` doesn't exist, it will get an error and fail. `fping`
is such a program that does this.
Thanks to Todd Resudek for reporting this issue.

Add /etc/protocols to make getprotobyname(3) work

---

package/erlinit/Config.in

I just noticed an out of date repository URL when looking at buildroot integration.

Update erlinit project repo url

---

scripts/merge-squashfs

Additional flags can be passed to mksquashfs by setting `NERVES_MKSQUASHFS_FLAGS`
for example:
`NERVES_MKSQUASHFS_FLAGS="-noD"`
This makes it possible to disable compression on the squashfs output for use with creating patch files.

Add NERVES_MKSQUASHFS_FLAGS

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This adds support for initializing UARTs. Prior to this version, if the
Linux kernel didn't initialize the UART, it would look like the UART
wasn't working. You could programmatically initialize the UART using
Circuits.UART, but initializing it in `erlinit` is simpler.

erlinit: bump to v1.7.0

---

patches/buildroot/0010-erlang-support-OTP-20-21-and-22.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 22.3.1 to 22.3.3. See the following release notes
for changes:
* https://erlang.org/download/OTP-22.3.3.README
* https://erlang.org/download/OTP-22.3.2.README

erlang: bump to 22.3.3

---

patches/buildroot/0011-fwup-bump-to-v1.7.0.patch

From the release notes:
In this release, `fwup` verifies writes to raw devices. Regular files
are not verified unless forced with the `--verify-writes` option. Writes
are verified as they're written. Since the final write with `fwup`
firmware updates is usually to toggle the active partition, corruption
can fail an update before the toggle occurs.
* New features
* Writes verification on raw devices. This may be forced with
`--verify-writes` or disabled with `--no-verify-writes`.
* The `boot` option works for GPT partitions now. `boot=true` will set
the GPT attribute flags appropriately. Since the archive creation
process replaces the `boot` parameter with raw flags, older versions
of `fwup` can apply updates that use this.
* Bug fixes
* After a write error was detected, `fwup` would …

fwup: bump to v1.7.0

---

patches/buildroot/0017-erlang-disksup-update-df-call-for-Busybox.patch

This fixes `:os_mon`'s `disksup` to invoke `df` so that it works with Busybox.
Now this works in Phoenix LiveDashboard:

erlang(disksup): update df call to work with Busybox

---

patches/buildroot/0010-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This is a major bump to Erlang/OTP and contains many changes. See
the release note at https://erlang.org/download/OTP-23.0.README.

erlang: bump to 23.0

---

patches/buildroot/0010-fwup-bump-to-v1.8.0.patch
support/docker/nerves_system_br/Dockerfile

fwup v1.8.0 adds support for redundant U-Boot environment blocks and
fixes memory leaks that don't affect Nerves.
To use redundant U-Boot environment blocks with Nerves, updates are
needed to the Elixir `uboot_env` package and this needs to be enabled on
Nerves systems.

fwup: bump to v1.8.0

---

patches/buildroot/0013-rpi-userland-bump-to-f97b1af1.patch
patches/buildroot/0014-rpi-firmware-bump-to-1.20200601.patch

rpi-firmware 1.20200527
rpi-userland f97b1af1b3e653f9da2c1a3643479bfd469e3b74
Tested on rpi3a w/wifi

rpi-firmware/userland bump to latest

---

patches/buildroot/0009-erlang-support-OTP-20-23.patch

This bumps Erlang from 23.0.2 to 23.0.3. Changes can be found at
https://erlang.org/download/OTP-23.0.3.README.

erlang: bump to 23.0.3

---

scripts/nerves-elixir.mk
scripts/rel2fw.sh

We've been using the `rootfs_overlay` name for them for a long time.
This removes some old references to remove any confusion of what the
right name is to use.
Note: The `nerves-elixir.mk` file is super old. It could probably be
deleted.

Update old references to rootfs-additions

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-23.patch

This bumps Erlang from 23.0.3 to 23.0.4. Changes can be found at
https://erlang.org/download/OTP-23.0.4.README.

erlang: bump version to 23.0.4

---

nerves_env.exs
scripts/nerves-env-helper.sh

This adds the `*_FOR_BUILD` environment variables so that it's possible
compile build tools. The `_FOR_BUILD` naming comes from Buildroot and
Autoconf.

Add environment variable overrides for host builds

---

patches/buildroot/0009-erlang-support-OTP-20-23.patch

This bumps Erlang from 23.0.4 to 23.1. Changes can be found at
https://erlang.org/download/OTP-23.1.README.

erlang: bump version to 23.1

---

.circleci/config.yml

From the circle CI Docs:
> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must specify tag filters for those jobs.
This PR _should_ fix CI so it always runs

Run CI for all branches, commits, and tags

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.1 to 23.1.1. Changes can be found at
https://erlang.org/download/OTP-23.1.1.README.

erlang: bump version to 23.1.1

---

package/nerves-config/Config.in

This package is a normal `config` now since it doesn't have any options.
This change fixes its presentation in `make menuconfig`.

nerves-config: change config type

---

patches/buildroot/0012-rpi-userland-bump-to-f73fca0.patch
patches/buildroot/0013-linux-firmware-add-raspberry-pi-settings.patch

This updates rpi-firmware, rpi-userland, and linux-firmware's Broadcom
WiFi driver installation to support Linux 5.4.
In addition to upgrading to Linux 5.4, systems will need to do the
following:
1. Change all references to `pi3-miniuart-bt` to `miniuart-bt`. This
affects `fwup.conf` and `config.txt` files.
2. Deselect `BR2_RPI_WIFI_FIRMWARE` from the `nerves_defconfig` and add
the following:
```
BR2_PACKAGE_LINUX_FIRMWARE=y
BR2_PACKAGE_LINUX_FIRMWARE_BRCM_BCM43XXX=y
```
3. Update the Linux kernel to Raspberry Pi's
`raspberrypi-kernel_1.20200902-1` release.
The update from Linux 4.19 to 5.14 appears to not require many changes
to the Linux configuration. The main one appears to be that the
Raspberry Pi's touchscreen input driver changed names.

Raspberry Pi Linux 5.4 support

---

patches/buildroot/0009-erlang-support-OTP-20-23.patch

This bumps Erlang from 23.1.1 to 23.1.4. Changes can be found at:
* https://erlang.org/download/OTP-23.1.2.README
* https://erlang.org/download/OTP-23.1.3.README
* https://erlang.org/download/OTP-23.1.4.README

erlang: bump version to 23.1.4

---

package/boardid/boardid.hash
package/boardid/boardid.mk

This release adds support for 16+ character serial numbers for
NervesKeys and non-default I2C addresses for ATECC chips.

boardid: bump to v1.10.0

---

patches/buildroot/0013-package-rpi-userland-support-aarch64.patch

This makes it possible to build rpi-userland on aarch64. Enabling rpi-userland with this patch will fix https://github.com/elixir-circuits/circuits_gpio/issues/84.

rpi-userland: support aarch64

---

patches/buildroot/0009-erlang-support-OTP-20-23.patch

This bumps Erlang from 23.1.4 to 23.1.5. See
https://erlang.org/download/OTP-23.1.5.README

erlang: bump version to 23.1.5

---

scripts/merge-squashfs

This fixes the following warning that started appearing when the
Raspberry Pi WiFi firmware blobs introduced a file with a space in it.
```
Pseudo modify file "lib/firmware/brcm/brcmfmac43430a0-sdio.ONDA-V80" does not exist in source filesystem.  Ignoring.
```
The real filename is `/lib/firmware/brcm/brcmfmac43430a0-sdio.ONDA-V80\ PLUS.txt`.
The changes here fix the issue that was accidentally stripping off
everything after the space character.
To test, I built a Raspberry Pi Zero project and then ran `mix
firmware.unpack` to verify that the `brcmfmac...` file existed. The
warning also went away with this change.

Support spaces in squashfs file paths

---

patches/buildroot/0009-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.2.1 to 23.2.2. See
https://erlang.org/download/OTP-23.2.2.README.

erlang: bump version to 23.2.2

---

patches/buildroot/0009-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.2.2 to 23.2.3. See https://erlang.org/download/OTP-23.2.3.README.

erlang: bump version to 23.2.3

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.2.4 to 23.2.5. See
https://erlang.org/download/OTP-23.2.5.README.

erlang: bump version to 23.2.5

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.2.5 to 23.2.7. See https://erlang.org/download/OTP-23.2.6.README and https://erlang.org/download/OTP-23.2.7.README.

 erlang: bump version to 23.2.7

---

scripts/scrub-otp-release.sh

To exercise this, one should create a `.noscrub` file in any
directory inside the release. any files in the same directory
will be excluded from scrubbing

Allow the ability to not scrub directories in the release dir

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-23.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.3.1 to 23.3.2. See
https://erlang.org/download/OTP-23.3.2.README.

erlang: bump version to 23.3.2

---

package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.hash
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk

This has the following comment:
```
firmware-nonfree (1:20190114-1+rpt11) buster; urgency=medium
* Update CYW43455 firmware
- brcm/brcmfmac43455-sdio.bin 7.45.229
- See: https://github.com/raspberrypi/linux/issues/3849
-- Serge Schneider <serge@raspberrypi.com>  Mon, 25 Jan 2021 10:17:21 +0000
```

Bump Broadcom WiFi firmware for Raspberry Pis

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-24.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 23.3.4 to 24.0.2. See
https://erlang.org/download/OTP-24.0.README,
https://erlang.org/download/OTP-24.0.1.README, and
https://erlang.org/download/OTP-24.0.2.README.

erlang: bump to 24.0.2

---

patches/buildroot/0013-erlang-add-RISC-V-to-the-supported-architectures.patch

Erlang runs on RISC-V, but it needs to be enabled in Buildroot. This
enables it.

erlang: enable RISC-V builds

---

patches/buildroot/0009-erlang-support-OTP-20-24.patch

This bumps Erlang from 24.0.2 to 24.0.3. See
https://erlang.org/download/OTP-24.0.3.README.

erlang: bump to 24.0.3

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

See https://github.com/nerves-project/erlinit/releases/tag/v1.10.0

erlinit: bump to v1.10.0

---

create-build.sh

Running on ARM 64 bit Linux I am getting the error `ERROR: 64-bit Linux required for running cross-compilers built by nerves-toolchain`. Updates the check to include ARM 64 linux.

Allow systems to be built on ARM 64 Linux

---

patches/buildroot/0009-erlang-support-OTP-20-24.patch

This particular change doesn't affect Nerves at all. It is only needed
if you're using Buildroot to compile Erlang packages. In spite of this,
I like keeping it accurate for those times when I work with Buildroot
outside of Nerves.

Fix ei version as passed via Buildroot

---

scripts/mksystem.sh

Buildroot has two tools for capturing SBOM-relevant information: `make
pkg-stats` and `make legal-info`. This makes it possible to add
`pkg-stats` and `legal-info` targets to the `make_opts` for your system
so that this info is captured. This is convenient so that you don't have
to rebuild a system to get the files when you need them. It also makes
it possible for tools to parse them and combine them with SBOM data from
the rest of your project.
The increase in system artifact size is minimal. Buildroot also includes
all of the source tarballs in its legal info, but that's like 800+ MB
for projects, so that's not included in this change.

Optionally include SBOM info in system artifacts

---

support/docker/nerves_system_br/Dockerfile
tests/run_tests.sh

The pkg-stats target requires a few more packages so install those for
users building package stats with their system builds. Also add
`pkg-stats` and `legal-info` to the smoke test targets since they both
seem easy to miss changing package requirements since they're not
regularly tested..

Dockerfile: add packages so make pkg-stats works

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-24.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 24.0.3 to 24.0.4. See
https://erlang.org/download/OTP-24.0.4.README.

erlang: bump to 24.0.4

---

scripts/merge-squashfs

If a directory under /home was in $PATH on MacOS, the path search for
`sed` was surprisingly slow. One an M1 MBP, adding `/home/missing` to
$PATH caused `mix firmware` to regularly take >40 seconds. Without that
in the $PATH, `mix firmware` almost always takes 10 or 11 seconds.
See the conversation at
https://elixirforum.com/t/mix-firmware-takes-very-long-time-to-run-how-to-debug/41201
for much, much worse experience on a different MBP. A huge thanks to
jpalley for figuring out that the slowdown was correlated with the
`/home` directory in the path.
This PR caches the absolute path to sed to avoid searching `$PATH` each
time. On an M1 MBP, this reduces the `mix firmware` time from 40 seconds
to about 11 seconds.

Work around slow path searches on MacOS

---

board/nerves-common/rootfs_overlay/etc/sysctl.conf

Related to elixir-toolshed/toolshed#81 and nerves-project/nerves_runtime#207
This PR adds a sysctl configuration file that allows all user groups to send an ICMP ping. Other params can be added to this config in the future, or it can be overridden by another rootfs overlay.
Out of the box on a Nerves target, `net.ipv4.ping_group_range` is set to `1 0` which causes an `:eacces` error when trying to open a socket to send an ICMP ping. This PR adjusts this parameter so that all users can send a ping.

Add sysctl config file

---

scripts/scrub-otp-release.sh

For whatever reason, the `find` command doesn't expand the exclusions on MacOS and so if you are attempting to skip scrubbing files, the task will fail. To get the proper variable expanded, we need to `eval` the call.
But adding `eval` on any other system breaks the script. So, check the OS and decide which to do first.
I have no idea why MacOS won't expand and the only hints on the internet were to `eval` to force expansions first. I've confirmed this works in MacOS and Linux

Fix scrubbing files on MacOS

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-24.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 24.0.4 to 24.0.5. See
https://erlang.org/download/OTP-24.0.5.README.

erlang: bump to 24.0.5

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This brings in experimental support for adding a runtime.exs to perform
runtime configuration of the OTP release in the firmware build.

erlinit: bump to v1.11.0

---

board/nerves-common/post-build.sh
scripts/ci-deploy.sh
scripts/scrub-otp-release.sh
scripts/scrub-target.sh
tests/smoke-test/rootfs_overlay/srv/erlang/bin/test
tests/smoke-test/rootfs_overlay/srv/erlang/erts-11.1.8/bin/erl
tests/smoke-test/rootfs_overlay/srv/erlang/erts-11.1.8/bin/erl.src
tests/smoke-test/rootfs_overlay/srv/erlang/erts-11.1.8/bin/start
tests/smoke-test/rootfs_overlay/srv/erlang/erts-11.1.8/bin/start.src
tests/smoke-test/rootfs_overlay/srv/erlang/erts-11.1.8/bin/start_erl.src
tests/smoke-test/rootfs_overlay/srv/erlang/releases/0.1.0/elixir
tests/smoke-test/rootfs_overlay/srv/erlang/releases/0.1.0/env.sh
tests/smoke-test/rootfs_overlay/srv/erlang/releases/0.1.0/iex
tests/smoke-test/run_scrubber.sh
tests/smoke-test/verify.sh

This wasn't a pull request initially because it took a minute for me to determine where this file came from on GitHub.  Using `/usr/bin/env` seems consistent with the other scripts here so opening as a pull request.
resolves [#650](https://github.com/nerves-project/nerves/issues/650)

Fix /bin/bash shebang to be /usr/bin/env bash

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-24.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 24.0.5 to 24.0.6. See
https://erlang.org/download/OTP-24.0.6.README.

erlang: bump to 24.0.6

---

.tool-versions
patches/buildroot/0009-erlang-support-OTP-20-24.patch
support/docker/nerves_system_br/Dockerfile

This bumps Erlang from 24.1 to 24.1.1. See
https://erlang.org/download/OTP-24.1.1.README.

erlang: bump to 24.1

---

mix.exs

It's very convenient to see the changelog in the hex diffs, so add it
first to the package.
Also remove the maintainers since that's handled by hex.pm
automatically.

Add changelog to hex package; remove maintainers

---

package/rpi-distro-firmware-nonfree/Config.in
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.hash
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk

See https://github.com/RPi-Distro/firmware-nonfree/blob/bullseye/debian/changelog
for all of the changes.

Bump RPi WiFi firmware

---

patches/buildroot/0013-Add-host-freetype-and-host-libjpeg.patch

Related issue: https://github.com/nerves-project/nerves_system_br/issues/609
This fixes problem with QT5 webengine build on various versions of buildroot by adding host-freetype and host-libjpeg dependency.

Add host freetype and host libjpeg dependencies to qt5webengine

---

mix.exs
nerves-env.cmake
nerves_env.exs

Hi, this PR adds a basic CMake toolchain file for cross-compiling environment and the path to the toolchain file is exported to a system environment variable `CMAKE_TOOLCHAIN_FILE`. 
This allows downstream libraries which use CMake to find the correct sysroot, and prevent CMake to search system libraries in the host environment.
The downstream libraries can decide whether they want to use the provided toolchain file. If yes, then they can append `-D CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}` to their CMake options.
For example, before applying this patch, CMake will search libraries available on the host, which causes the linker to try to link the NIF shared library to libraries on the host, and this can result in either
- a fatal error, when the host's architecture is different from …

export `CMAKE_TOOLCHAIN_FILE` for downstream libraries which use CMake

---

scripts/nerves-env-helper.sh

Buildroot symlinks /usr to . so it's unnecessary to refer to /usr. This
mirrors a similar change to nerves_env.exs.

nerves-env-helper.sh: remove host references to /usr

---

.tool-versions
support/docker/nerves_system_br/Dockerfile

When updating to OTP 24.2.1, these updates were missed. Luckily, it
doesn't look like there's a meaningful different with 24.2, but they
should match anyway.

Bump Erlang versions for Docker image

---

package/bborg-overlays/Config.in
package/bborg-overlays/bborg-overlays.mk

Upstream Beagleboard now looks for overlays in `/boot/overlays` first.
It then tries `/lib/firmware` which is the directory that
`nerves_system_bbb` has always checked.
This lets systems modify the path if they're able to migrate to the new
location. The default is the still `/lib/firmware`.

bborg-overlays: support changing overlay paths

---

package/nerves_heart/nerves_heart.mk

This installs `nerves_heart` to the staging directory so that it's
possible to use `include_erts: true` when making releases. Without this
change, the staging directory has the default version of Erlang's
`heart` that doesn't pet the hardware watchdog. That means that if you
use `include_erts: true` in your release (likely indirectly via the
Nerves tooling), then the device will reboot when the hardware watchdog
times out.

nerves_heart: support include_erts: true

---

package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.hash
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk

From the changelog:
* Add ability to choose between 43436 and 43436S using update-alternatives
* The shipping firmware for the SYN43436P does not support 4-way
handshake offloading. This new firmware (version string "Version:
9.88.4.77 CRC: 143f9f15 Date: Thu 2022-03-31 17:25:16 CST Ucode Ver:
1043.20743 FWID: 01-3b307371") fixes that.

Update RPi WiFi to 20210315-3+rpt5 + Zero 2W fix

---

package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk

The rpi-distro-firmware-nonfree repository really is a Debian package
script. I had sync'ed the files and symlinks in the firmware directory,
but there were a couple that I missed in the Debian post install
script.
This fixes an issue where the Raspberry Pi Zero 2W's WiFi module's
firmware wouldn't load with Linux 5.15.

rpi-distro-firmware-nonfree: add symlinks

---

nerves-env.cmake

Set `CMAKE_SYSTEM_PROCESSOR` to `$ENV{TARGET_ARCH}`. 
Some libraries (e.g., xnnpack) (implicitly) require this variable to be set when cross-compiling.

set system processor

---

README.md

We now officially support GRiSP2, adding [nerves_system_grisp2](https://github.com/nerves-project/nerves_system_grisp2).
In this repo [nerves_system_br](https://github.com/nerves-project/nerves_system_br), all we need seems to be just add a link to [nerves_system_grisp2](https://github.com/nerves-project/nerves_system_grisp2) in `README.md`.

Add nerves_system_grisp2 link to README.md

---

.circleci/config.yml
support/docker/nerves_system_br/Dockerfile
support/docker/nerves_system_br/setup-packages.sh

Currently I develop primarily on an M1 MacBook Pro - When it comes to building Nerves systems, it seems that there's only first class support for `x86_64`. 
This PR aims to introduce small changes to the Dockerfile and CI configuration that will enable `aarch64` host systems (such as M1 machines) to build Nerves systems using Docker. I've tested it on some internal system repositories with success.
* Enable multi-arch builds in CircleCI
* Modify `Dockerfile` to work with both targets (`linux/amd64` and `linux/arm64`)
* Add a `setup-packages.sh` script used during the Docker build to use the proper method of installing `i386` libraries for systems.
NOTE: To fully support `aarch64` host machines, we also need to enable `aarch64` Linux toolchains over at: …

Enable aarch64 compatibility in the Docker image

---

patches/buildroot/0012-Revert-package-libp11-bump-to-version-0.4.12.patch

libp11 0.4.12 does not work with nerves_key_pkcs11 right now. It's
unclear when we'll figure this out at the moment, so revert the update
for now.

Revert libp11 to 0.4.11 to fix pkcs11 issue

---

nerves-env.sh

For #202 
* https://www.shellcheck.net/wiki/SC2046 - Quote this to prevent word splitting.
* https://www.shellcheck.net/wiki/SC2048 - Use "$@" (with quotes) to prevent whitespace problems.
* https://www.shellcheck.net/wiki/SC2124 - Assign as array, or use * instead of @ to concatenate.
* https://www.shellcheck.net/wiki/SC2166 - `-a` is not well defined
* https://www.shellcheck.net/wiki/SC2128 - Expanding an array without an index only gives the first element.
* https://www.shellcheck.net/wiki/SC2086 - Double quote to prevent globbing and word splitting.
* https://www.shellcheck.net/wiki/SC2181 - Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.

Fixup shellchecks for nerves-env.sh

---

support/docker/nerves_system_br/setup-packages.sh

For #202
* https://www.shellcheck.net/wiki/SC2129 - Consider using { cmd1; cmd2; } >> file instead of individual redirects.

Fix shellcheck for setup-packages.sh

---

.tool-versions
patches/buildroot/0007-erlang-support-OTP-21-25.patch
support/docker/nerves_system_br/Dockerfile

See https://www.erlang.org/patches/otp-25.1
There was a vulnerability referenced in ssl and it was suggested that updating to 25.1 is best.

erlang: bump to 25.1

---

patches/buildroot/0007-erlang-support-OTP-21-25.patch

This removes the patch we had to force deterministic compiles with
OTP 25 since it looks like the new flag does that and more.

Use OTP 25.1's --enable-deterministic-build flag

---

nerves-env.sh

This was mistakenly changed when enabling shellchecks. Apparently the arg will only be in $0 when sourcing, so using $1 causes failures even when bash was correctly used to source.
Wasn't detected locally because zsh was used and only seen recently from some CI processes were forcefully using bash 🤦

Fix checking bash source in nerves-env.sh

---

scripts/rel2fw.sh

Fixes https://github.com/nerves-project/nerves/issues/576
Allows us to place temporary items in the specific build path rather than in `_build` root.
Requires https://github.com/nerves-project/nerves/pull/793 to be utilized within the firmware build process of the common Nerves tooling

Use `MIX_BUILD_PATH` if specified

---

scripts/scrub-otp-release.sh

Since executables are already checked for compatibility with the target
processor, it's unnecessary to fail for strip errors. If strip fails,
just move on and print out a warning. This fixes issues with precompiled
Rust binaries that shows up as the following error:
```
not enough room for program headers, try linking with -N
```
Since the Rust binaries are precompiled, you can't relink, but it's
unnecessary anyway since the binaries work fine.

Don't fail build for strip errors

---

.circleci/config.yml

This registry is free for open source and should work just as well. It will require users to change the location for fetching to `ghcr.io/nerves-project/nerves_system_br`

Switch to use GitHub Container Registry

---

patches/buildroot/0015-erlang-revert-multiline-editing-for-OTP-26.0.patch

Multiline editing doesn't work over ssh yet. Upstream fixes are in
progress. This unblocks OTP 26.0 use with Nerves for the time being.

erlang: disable multiline editing for OTP-26.0

---

scripts/merge-squashfs

Part of https://github.com/nerves-project/nerves/issues/877 for adding more useful output during the firmware build process.
https://github.com/nerves-project/nerves/issues/876 shows cases where `mix firmware` fails to build. In reproducing, I found that `merge-squashfs` was failing silently. Specifically at this line because `2>/dev/null` was forwarding stderr to be ignored.
Instead, this changes to let stderr through so more helpful messages can be reviewed

Don't consume stderr in `merge-squashfs`

---

create-build.sh

When nerves_system_br or its patches change, there's a warning that you
may need to build clean. It requires an acknowledgment. When building
with a non-interactive terminal, like when being called from Elixir,
it's not possible to acknowledge it. This detects the case and prints a
warning about blindly continuing since that's often the right answer for
expert users anyway. There's a pause, though, so it's easier to see in
the flood of Buildroot compilation messages.

Don't prompt on non-interactive terminals

---

patches/buildroot/0015-package-python-pylibfdt-add-host-python-package.patch
patches/buildroot/0016-boot-uboot-add-host-python-pylibfdt-dependency-if-ne.patch

This fixes a U-Boot build error on MangoPi and an Allwinner A64
configurations.

buildroot: add host-pylibfdt updates for new U-Boot

---

patches/buildroot/0015-package-pppd-bump-version-to-2.5.0.patch

This pulls in the upstream Buildroot patch for 2.5.0 that hasn't made it
to an official Buildroot release yet.

pppd: bump to 2.5.0 to fix GCC 13 compiler error

---

package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.hash
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk

This add RPi 5-specific links to support the BCM43455 WiFi module.
It also contains about 2 years worth of changes since the previous
version. The changelog is at
https://github.com/RPi-Distro/firmware-nonfree/blob/88aa085bfa1a4650e1ccd88896f8343c22a24055/debian/changelog.

rpi-distro-firmware-nonfree: bump to 1:20230210-5+rpt2

---

scripts/merge-squashfs

This is a proposed solution to https://github.com/nerves-project/nerves/issues/876.
On macOS, `mktemp` will create a temporary directory in `/var/...` which is on a case-insensitive volume. The `merge-squashfs` script will fail when Buildroot packages contain files that differ only in their case.
By adding the `-p ''` argument to `mktemp`, it is forced to honor the `$TMPDIR` environment variable, which the user could specify ahead of time as a special directory on a case-sensitive volume.

Force mktemp to honor $TMPDIR in merge-squashfs script

---

scripts/merge-squashfs

This is a follow-up to #778 and a proposed fix for #781.
Here's what I know:
- `mktemp` on macOS 13 does not support the `-p` option (as reported in #781)
- The `-t` option is problematic
- The option behaves wildly differently between macOS and Linux
- Ubuntu 18 manpages claim the `-t` option is deprecated
- The original fallback invocation of `mktemp -d -t 'merge-squashfs-tmp'` doesn't even work on Linux; the template string requires "X" characters as placeholders
- `mktemp` does not consistently honor `$TMPDIR`
- Linux `mktemp` honors `$TMPDIR` by default
- macOS `mktemp` does NOT honor `$TMPDIR` by default
So, my proposed solution avoids `-t` and `-p` and is about as simple and explicit as possible, and it has been tested as working equally well on macOS 13, 14, and Ubuntu 18, and …

Add explicit check for $TMPDIR before calling mktemp in merge-squashfs

---

.tool-versions
patches/buildroot/0007-erlang-support-OTP-21-26.patch
patches/buildroot/0015-Fix-for-compilation-errors-due-to-libei-naming-confl.patch
support/docker/nerves_system_br/Dockerfile

Updated erlang to 26.2.4.
Added patch to fix compilation errors when `libei` is present, discussed [here](https://github.com/erlang/otp/issues/8244).
This fix is merged into `master` but hasn't made it into releases yet.

Updated erlang to 26.2.4, added patch for libei naming conflicts

---

create-build.sh
support/docker/nerves_system_br/docker-entrypoint.sh

With https://github.com/nerves-project/nerves/pull/972, `useradd` fails to copy the /etc/skel to the new home directory.
This fixes by manually doing this copy.

Manually create skel

---

create-build.sh

This allows an env var to be set to ignore the case-sensitivity check since that may be a very common case. The error is now big and colorized
Also adjusts a few pieces to satisfy the shellcheck

Adjust case-sensitive FS check

---

create-build.sh

The rm *.sensitive done here can fail if it was previously removed (on line 74). The script is running with `set -e` so this will cause the script to exit unexpectedly. Adding a `-f` to the rm will fix it

Don't fail on rm *.sensitive if it was already removed earlier in script

---

package/rpi-distro-bluez-firmware/rpi-distro-bluez-firmware.hash
package/rpi-distro-bluez-firmware/rpi-distro-bluez-firmware.mk
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.hash
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk
package/rpi-libcamera/rpi-libcamera.hash
package/rpi-libcamera/rpi-libcamera.mk
package/rpicam-apps/rpicam-apps.hash
package/rpicam-apps/rpicam-apps.mk

- **rpi-distro-bluez-firmware: bump to 78d6a07**
- **rpi-distro-firmware-nonfree: bump version to 20230625-2+rpi2**
- **rpi-libcamera: bump to v0.2.0+rpt20240418**
- **rpicam-apps: bump to 1.4.4**

Bump Raspberry Pi firmware and libcamera packages

---

support/docker/nerves_system_br/Dockerfile

This pulls in many improvements from
https://github.com/CircleCI-Public/cimg-base/blob/main/Dockerfile.template
to address non-root use.
The most important of these are adding `./.local/bin` to the PATH and
password-less sudo. Others include environment variable updates, fixing
the cached ssh host key path and other improvements from the CircleCI
template.

Update Dockerfile for better non-root use

---

scripts/merge-squashfs

This is a temporary fix for an issue that prevents building firmware on
macOS if the Nerves system contains any files with names that collide on
a case-insensitive filesystem like APFS. See nerves-project/nerves#876.
When running `mix firmware`, warnings in the following format may
indicate that some things may not work as expected:
```
Pseudo modify file "path/to/file" does not exist in source filesystem.  Ignoring.
```

Run unsquashfs with force flag when merging rootfs

---

scripts/scrub-otp-release.sh

The Elixir versioning reason is super old, and hopefully we're years
past anyone running into that.
Nowadays, it seems way more common to run into libraries that build to their
source directories and don't do the right thing when the `MIX_TARGET`
changes.

Update scrub warning to be more helpful

---

scripts/scrub-otp-release.sh

It turns out that the XLA shared libraries are marked read-only and
because of this, they fail to be stripped. This unconditionally marks
executables as writable before stripping them to avoid this being a
reason to error out.

Ensure executables are writable before stripping

---

package/erlinit/erlinit.hash
package/erlinit/erlinit.mk

This version adds the `--core-pattern` option.

erlinit: bump to 1.14.2

---

Config.in
package/tpm2-tss-engine/0001-Allow-disabling-of-digest-sign-operations.patch
package/tpm2-tss-engine/0002-Fix-mismatch-of-OpenSSL-function-signatures-that-cause-errors-with-gcc-14.patch
package/tpm2-tss-engine/Config.in
package/tpm2-tss-engine/tpm2-tss-engine.hash
package/tpm2-tss-engine/tpm2-tss-engine.mk
patches/buildroot/0016-update-tpm2-tss-to-4.1.3.patch

This PR contains a few modifications for a [Trusted Platform Module](https://en.wikipedia.org/wiki/Trusted_Platform_Module) (TPM) to work with Nerves:
- The `tpm2-tss-engine` package was added so that the BEAM can communicate with the TPM via an OpenSSL engine.
- `tpm2-tss` is a core library for communicating with TPMs. v3 was incompatible, so we patched it to v4.
- We pulled in a patch to support compilation with GCC 14.
The Elixir TPM library is available here:
https://github.com/redwirelabs/tpm
This is also compatible with the open source [tpm2-tools](https://github.com/tpm2-software/tpm2-tools) tooling.

Add TPM support

---

scripts/rel2fw.sh

This would typically be invoked by `mix firmware` further up the stack. It is at the right moment to allow operating on the squashfs file system before it is packed up into the fw file.
The primary purpose is to allow signing the root filesystem for use with dm-verity.

Add option to rel2fw.sh to allow post-processing

---

package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.hash
package/rpi-distro-firmware-nonfree/rpi-distro-firmware-nonfree.mk

This also includes symlinks for the CM5 and 500.
The changelog reads:
```
[ Phil Elwell ]
* brcm80211: cypress: Add 43455 firmware for WPA3 offload
[ Serge Schneider ]
* d/c/brcm80211/defines: update version
* Update linux-support to 6.6.31+rpt
```

rpi-distro-firmware-nonfree: bump to 1:20230625-2+rpt3
