scripts/scrub-otp-release.sh
This lets the `scrub-otp-release.sh` script allow statically linked executable files.
=> scrub-otp-release.sh: Support statically linked executables

README.md
=> Removed word

nerves_env.exs
Similar to the pull request I made for nerves-env.sh in January '16
=> Add environment variables to work with erlang.mk

scripts/merge-squashfs, scripts/rel2fw.sh, scripts/scrub-otp-release.sh
fixes https://github.com/nerves-project/nerves/issues/114
=> quote when directory may contain special characters or spaces

nerves_env.exs
=> fix warnings for elixir 1.5

nerves_env.exs
Previously you'd get an exception when this happened. I'm able to trigger
this by pressing CTRL+C while the toolchain is downloading. I'm pretty
sure that I've run into this before with a failed download.
=> Improve error message if toolchain isn't found

scripts/rel2fw.sh
=> Add error for rel2fw rootfs_additions

Config.in, package/nerves-config/Config.in, package/nerves-config/nerves-config.mk, package/nerves_heart/Config.in, package/nerves_heart/nerves_heart.hash, package/nerves_heart/nerves_heart.mk
See https://github.com/nerves-project/nerves_heart for details
=> Add Nerves support for Erlang's heart ❤️

scripts/rel2fw.sh
This allows the `-a` flag to be supplied multiple times.
=> Allow for multiple rootfs additions.

patches/buildroot/0016-package-ncurses-enable-widechar-for-host-build.patch
=> Pull in host-ncurses/linux-menuconfig fix

package/bborg-overlays/bborg-overlays.mk
This also needs another commandline option to ignore some warnings.
=> bborg-overlays: bump to latest commit

patches/buildroot/0013-fix-qtwebengine-enable-condition.patch
This should fix #166. I have not tested it, though.
=> qt5webengine: fix broken enable condition

scripts/nerves-env-helper.sh
Closes https://github.com/nerves-project/nerves_system_br/issues/177
=> Adds an additional solution to the Erlang OTP version error.

scripts/scrub-otp-release.sh
While I can't reproduce issue #169, the use of `file` to find ELF
binaries is questionable anyway, so this refactors the script to not
call it. I would expect this to fix #169.
=> Remove call to 'file' in scrub script

scripts/scrub-otp-release.sh
This fixes the scrubber failing when releases contain shell scripts.
=> Fix issue with calling readelf and give better error

patches/buildroot/0014-qt5webengine-propagate-parallel-flag-to-ninja.patch
=> Pull in qt5webengine parallel compile fix

.circleci/config.yml
Can't push unless you've built something first.
=> Fix circle workflow sequence

support/docker/nerves_system_br/Dockerfile
=> Update fwup version in dockerfile

patches/buildroot/0009-erlang-bump-to-21.0.patch
See http://erlang.org/pipermail/erlang-questions/2018-August/096230.html
=> erlang: bump to 21.0.6

board/nerves-common/post-createfs.sh, create-build.sh, nerves-env.sh, scripts/buildroot-state.sh, scripts/ci-build.sh, scripts/download-buildroot.sh, scripts/merge-squashfs, scripts/mksyslinuxfs.sh, scripts/mksystem.sh, scripts/nerves-env-helper.sh, scripts/rel2fw.sh, support/docker/nerves_system_br/docker-entrypoint.sh, tests/run_tests.sh
With any luck this fixes our support for NixOS. See #240.
=> Switch to finding bash via env

patches/buildroot/0012-erlang-bump-to-21.2.5.patch
See http://erlang.org/download/OTP-21.2.5.README
=> erlang: bump to 21.2.5

patches/buildroot/0012-erlang-bump-to-21.2.6.patch
See http://erlang.org/download/OTP-21.2.6.README
=> erlang: bump to 21.2.6

patches/buildroot/0012-erlang-bump-to-21.3.3.patch, patches/buildroot/0015-erlang-enable-deterministic-compile-flag.patch
See http://erlang.org/download/OTP-21.3.3.README
=> erlang: bump to 21.3.3

patches/buildroot/0012-erlang-bump-to-21.3.6.patch, patches/buildroot/0015-erlang-enable-deterministic-compile-flag.patch, support/docker/nerves_system_br/Dockerfile
See http://erlang.org/download/OTP-21.3.6.README
=> erlang: bump to 21.3.6

patches/buildroot/0012-erlang-support-OTP-20-21-and-22.patch
See http://erlang.org/pipermail/erlang-questions/2019-June/098068.html
for release announcement.
=> erlang: bump to 22.0.3

patches/buildroot/0011-erlang-support-OTP-20-21-and-22.patch, support/docker/nerves_system_br/Dockerfile
See
http://erlang.org/pipermail/erlang-questions/2019-September/098502.html
for release notes.
=> erlang: bump to 22.1.1

patches/buildroot/0010-erlang-support-OTP-20-21-and-22.patch
See https://erlang.org/download/OTP-22.3.1.README
=> erlang: bump to 22.3.1

support/docker/nerves_system_br/Dockerfile
Looks like this package is already in the package list here: https://github.com/mattludwigs/nerves_system_br/blob/master/support/docker/nerves_system_br/Dockerfile#L36. I could be missing some detail though.
=> Remove duplicate package

Config.in, package/nerves_initramfs/Config.in, package/nerves_initramfs/nerves_initramfs.hash, package/nerves_initramfs/nerves_initramfs.mk
I'm starting to use this in all the rpi systems. After talking with Frank, we decided its prob easier to include it here rather than copy configs in each project.
=> nerves_initramfs: new package

patches/buildroot/0009-erlang-support-OTP-20-23.patch, support/docker/nerves_system_br/Dockerfile
fwup 1.8.1 doesn't have any meaningful changes over 1.8.0 for CI.
=> Dockerfile: bump fwup to 1.8.1

support/docker/nerves_system_br/Dockerfile
should fix [this](https://app.circleci.com/pipelines/github/nerves-project/nerves_system_rpi3a/266/workflows/5d121e65-e2db-415f-906a-6ecdc9d24a47/jobs/677) issue
=> Update Dockerfile to install pip3

tests/run_tests.sh
https://github.com/koalaman/shellcheck/wiki/SC2115
=> Fix SC2115 of tests/run_tests.sh

patches/buildroot/0012-package-fwup-bump-to-v1.9.0.patch, support/docker/nerves_system_br/Dockerfile
See https://github.com/fwup-home/fwup/releases/tag/v1.9.0.
=> fwup: bump to v1.9.0

nerves_env.exs
Fixes https://github.com/nerves-networking/vintage_net_wifi/issues/66.
=> Reorder PATH and LD_LIBRARY update order; cleanup

CHANGELOG.md
Hopefully make it a little easier for people to understand
Question: What does "extended firmware" mean? Is that just if you have your own `fwup.conf` that you're using?
=> 1.18 changelog improvement

.tool-versions, patches/buildroot/0007-erlang-support-OTP-21-25.patch, support/docker/nerves_system_br/Dockerfile
=> erlang: bump to 25.0

.tool-versions, patches/buildroot/0007-erlang-support-OTP-21-25.patch
This doesn't include the update to DockerFile since it hasn't been
posted yet.
=> erlang: bump to 25.0.3

.circleci/config.yml, nerves-env.sh, scripts/rel2fw.sh, scripts/scrub-otp-release.sh, scripts/shellchecks.sh, support/docker/nerves_system_br/setup-packages.sh
Fixes https://github.com/nerves-project/nerves_system_br/issues/202 and https://github.com/nerves-project/nerves_system_br/issues/203
=> Add shellchecks to CI

patches/buildroot/0016-erlang-add-aarch64-div-rem-JIT-fix.patch
See https://github.com/erlang/otp/pull/7567 for details.
=> erlang: add aarch64 div/rem JIT fix

scripts/scrub-otp-release.sh
Based on #771 - Thanks to @CaptChrisD for getting it started!
`find` in that last few MacOS versions have been slightly different from one another which causes confusing errors when trying to use the `-not -path` arguments to filter out files from stripping.
This changes to use simple bash loop to filter those out since the `.noscrub` directories are usually few and this reduces changes of future OS version randomly breaking (and us having to learn all the nuances of `find` between systems)
=> Switch to bash loop for scrubbing away executables

package/rpi-libcamera/Config.in, package/rpi-libcamera/rpi-libcamera.hash, package/rpi-libcamera/rpi-libcamera.mk, package/rpicam-apps/rpicam-apps.hash, package/rpicam-apps/rpicam-apps.mk
- **rpi-libcamera: bump to v0.5.0+rpt20250429**
- **rpicam-apps: bump to 1.7.0**
=> Bump rpi-libcamera and rpicam-apps to latest
